# Generated by Django 5.0.3 on 2024-04-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma_management_profile',
            name='FIRST_NAME',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='diploma_management_profile',
            name='LAST_NAME',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='diploma_management_profile',
            name='MIDDLE_NAME',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='academic_program',
            name='DESCRIPTION',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='DESCRIPTION',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='DESCRIPTON',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='diploma_management_profile',
            name='COMMENT',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='COMMENTS',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
