# Generated by Django 5.0.3 on 2024-04-25 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_diploma_management_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='LEARNING_STATUS_TYPE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.learning_status_type'),
        ),
    ]
