# Generated by Django 5.0.3 on 2024-04-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_student_learning_status_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma_management_profile',
            name='APPORVEDY',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diploma_management_profile',
            name='DATE_UPDATED',
            field=models.DateField(auto_now=True),
        ),
    ]
