# Generated by Django 5.0.3 on 2024-05-12 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_remove_diploma_management_profile_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_intake_session_academic_program_curriculum',
            name='ACADEMIC_INTAKE_SESSION_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_app.academic_intake_session'),
        ),
        migrations.AlterField(
            model_name='academic_intake_session_academic_program_curriculum',
            name='ACADEMIC_PROGRAM_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_app.academic_program'),
        ),
        migrations.AlterField(
            model_name='academic_intake_session_academic_program_curriculum',
            name='CURRICULUM_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_app.curriculum'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='ACADEMIC_PROGRAM_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_app.academic_program'),
        ),
        migrations.AlterField(
            model_name='diploma_management_profile',
            name='STUDENT_ID_NUMBER',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_app.student'),
        ),
        migrations.AlterField(
            model_name='diploma_management_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='ACADEMIC_LEVEL_TYPE_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_app.academic_level_type'),
        ),
        migrations.AlterField(
            model_name='student',
            name='LEARNING_STATUS_TYPE_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_app.learning_status_type'),
        ),
        migrations.AlterField(
            model_name='student_academic_intake_session_academic_program',
            name='ACADEMIC_INTAKE_SESSION_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_app.academic_intake_session'),
        ),
        migrations.AlterField(
            model_name='student_academic_intake_session_academic_program',
            name='ACADEMIC_PROGRAM_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_app.academic_program'),
        ),
        migrations.AlterField(
            model_name='student_academic_intake_session_academic_program',
            name='STUDENT_ID_NUMBER',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_app.student'),
        ),
    ]
