# Generated by Django 5.0.3 on 2024-05-21 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_rename_apporvedy_diploma_management_profile_apporved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='ACADEMIC_PROGRAM_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.academic_program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='BIRTH_PLACE',
            field=models.CharField(max_length=255),
        ),
    ]
