# Generated by Django 5.0.3 on 2024-05-21 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_alter_curriculum_academic_program_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_intake_session_academic_program_curriculum',
            name='ACADEMIC_INTAKE_SESSION_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.academic_intake_session'),
        ),
        migrations.AlterField(
            model_name='academic_intake_session_academic_program_curriculum',
            name='ACADEMIC_PROGRAM_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.academic_program'),
        ),
        migrations.AlterField(
            model_name='academic_intake_session_academic_program_curriculum',
            name='CURRICULUM_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.curriculum'),
        ),
        migrations.AlterField(
            model_name='student_academic_intake_session_academic_program',
            name='ACADEMIC_INTAKE_SESSION_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.academic_intake_session'),
        ),
        migrations.AlterField(
            model_name='student_academic_intake_session_academic_program',
            name='ACADEMIC_PROGRAM_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.academic_program'),
        ),
        migrations.AlterField(
            model_name='student_academic_intake_session_academic_program',
            name='STUDENT_ID_NUMBER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.student'),
        ),
    ]
