# Generated by Django 5.0.3 on 2024-05-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_alter_diploma_management_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree',
            old_name='DESCRIPTON',
            new_name='DESCRIPTION',
        ),
        migrations.AlterField(
            model_name='academic_intake_session_academic_program_curriculum',
            name='STATUS_NAME',
            field=models.BooleanField(default=True),
        ),
    ]
