# Generated by Django 5.0.3 on 2024-05-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_rename_descripton_degree_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='DEGREE_STATUS',
            field=models.BooleanField(),
        ),
    ]
