# Generated by Django 5.0.3 on 2024-05-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_alter_degree_degree_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diploma_management_profile',
            old_name='APPORVED',
            new_name='APPROVED',
        ),
    ]
