# Generated by Django 5.0.3 on 2024-05-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_rename_apporved_diploma_management_profile_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='DESCRIPTION',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
