# Generated by Django 5.0.3 on 2024-05-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_alter_degree_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_program',
            name='DESCRIPTION',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='DESCRIPTION',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='DESCRIPTION',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='diploma_management_profile',
            name='COMMENT',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='COMMENTS',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
